### PR TITLE
Create ARM target

### PR DESCRIPTION
**Pull request by ghost**
Created an ARM64 target, removed the irrelevant parts of the code (that will be replaced by ARM equivalents) and implemented MSR Read/Write.

### CODE REVIEW

**Comment by GermanAizek** [comment]
@SecurityAndStuff, thank you very much for your contribution, but this does not solve driver signature problem.
It is necessary to promote the acute problem of WinRing0 critical vulnerability and find among people who can sign and make a release from modified sources.
I will build ARM configuration this week and check it on my single-board computer.

**Comment by GermanAizek** [comment]
@SecurityAndStuff, I forgot to add you from the last pull request to README.md, excuse me.

**Comment by ghost** [comment]
Looking [here](https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage), an entity doesn’t seem mandatory.

For example: https://support.certum.eu/en/code-signing-required-documents/

**Comment by ghost** [comment]
This still doesn't solve the issue of breaking SYSTEM -> Kernel security boundary, but that's not really possible without breaking parts of the driver's functionality.

I am not really sure Microsoft will sign the driver due to the security issues it presents, `IOCTL_OLS_READ_MEMORY` and `IOCTL_OLS_WRITE_MEMORY` would have to and should be removed.

**Pull request merged**
